name: "Detect snapshot"

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    detectSnapshot:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectSNAPSHOT.sh
